name: Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn test
  test_specified_months:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: version
        with:
          token: ${{ github.token }}
          tag_prefix: ${{ github.ref_name }}/v
          release_months: |
            July
            January
      - run: git ls-remote --tags | grep refs/tags/${{ steps.version.outputs.new_tag }}
      - uses: actions/github-script@v6
        if: always() && steps.version.outcome == 'success'
        with:
          script: |
            github.rest.git.deleteRef({
              ...context.repo,
              ref: 'tags/${{ steps.version.outputs.new_tag }}',
            })
  test_unspecified_months:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: version
        with:
          token: ${{ github.token }}
          tag_prefix: ${{ github.ref_name }}/v
      - name: Expect correct tag
        run: |
          expect="refs/tags/${{ github.ref_name }}/v""$(date '+%y.%-m')"".0"
          echo "Expecting tag '$expect' to exist"
          git ls-remote --tags | grep "$expect"
      - uses: actions/github-script@v6
        if: always() && steps.version.outcome == 'success'
        with:
          script: |
            github.rest.git.deleteRef({
              ...context.repo,
              ref: 'tags/${{ steps.version.outputs.new_tag }}',
            })
